refactor: get rid of 'ProtocolParametersStore' in aggregator
This legacy implementation is replaced by a fake implementation of the
'ProtocolParametersStorer' trait, as it used for tests only.

Attempt to fix temporal effects at startup (fast epochs) resulting in
error: '`mithril-aggregator genesis bootstrap` exited with code: 1'